version: '3.7'

services:
  web:
    build: ./
    container_name: blackout_cloud_web
    restart: always
    command: bash entrypoint.sh
    volumes:
      - .:/usr/src/app
      - ./static:/usr/src/app/static
      - ./media:/usr/src/app/media
    ports:
      - 8000:8000
    env_file:
      - ./.env_prod
    depends_on:
      - db

  db:
    image: postgres:12
    container_name: blackout_cloud_db
    volumes:
      - audio_library_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env_prod
    ports:
      - 5432:5432

  nginx:
    build: ./nginx
    container_name: blackout_cloud_nginx
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./static:/static
      - ./media:/media
    depends_on:
      - web

volumes:
  audio_library_postgres_data: